import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#050505" },
  appShell: { flex: 1, backgroundColor: "#050505", flexDirection: "row" },
  drawerLayer: {
    bottom: 0,
    flexDirection: "row",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 20,
  },
  drawerBackdrop: {
    backgroundColor: "rgba(0, 0, 0, 0.58)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  mainPane: { backgroundColor: "#050505", flex: 1 },
  topBar: {
    alignItems: "center",
    backgroundColor: "#050505",
    borderBottomColor: "#1f1f1f",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 62,
    paddingHorizontal: 14,
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "#1a1a1a",
    borderColor: "#303030",
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    marginRight: 12,
    width: 40,
  },
  iconButtonText: { color: "#ffffff", fontSize: 20, fontWeight: "800" },
  topBarTitleBlock: { flex: 1 },
  topBarTitle: { color: "#ffffff", fontSize: 18, fontWeight: "800" },
  topBarSubtitle: { color: "#8f8f8f", fontSize: 12, marginTop: 2 },
  newChatSmallButton: {
    alignItems: "center",
    backgroundColor: "#1a1a1a",
    borderColor: "#303030",
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  newChatSmallButtonText: { color: "#ffffff", fontSize: 24, lineHeight: 28 },



















  flowScroll: { backgroundColor: "#050505", flex: 1 },
  flowContent: {
    paddingHorizontal: 16,
    paddingVertical: 18,
    paddingBottom: 34,
  },
  flowHeaderRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
    marginBottom: 14,
  },
  flowHeaderTextBlock: { flex: 1, minWidth: 210 },
  flowTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 6,
  },
  flowSubtitle: { color: "#9ca3af", fontSize: 14, lineHeight: 20 },
  backToChatButton: {
    alignItems: "center",
    backgroundColor: "#f2f4f8",
    borderRadius: 10,
    flexShrink: 0,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 12,
  },
  backToChatButtonText: {
    color: "#050505",
    fontSize: 13,
    fontWeight: "900",
  },
  flowCard: {
    backgroundColor: "#111111",
    borderColor: "#262626",
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 14,
    padding: 14,
  },

  flowCardTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 4,
  },






  flowEmptyBox: {
    alignItems: "center",
    backgroundColor: "#0b0b0b",
    borderColor: "#242424",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 120,
    padding: 18,
  },
  flowEmptyText: {
    color: "#b8b8b8",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },















  flowEmptyExampleText: {
    color: "#8f8f8f",
    fontSize: 12,
    lineHeight: 19,
    marginTop: 10,
    textAlign: "center",
  },
  todayMeTypeLabel: {
    color: "#8f8f8f",
    fontSize: 11,
    fontWeight: "900",
  },
  todayMeActionRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  todayMeTinyButton: {
    alignItems: "center",
    borderColor: "#3a3a3a",
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  todayMeTinyButtonText: {
    color: "#f2f4f8",
    fontSize: 18,
    fontWeight: "900",
  },
  todayMeGroup: {
    gap: 8,
    marginTop: 14,
  },
  todayMeGroupTitle: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: "900",
  },
  todayMeItem: {
    backgroundColor: "#151515",
    borderColor: "#303030",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  todayMeTitle: {
    color: "#f2f4f8",
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 20,
  },
  todayMeStatus: {
    color: "#9cc7ff",
    fontSize: 12,
    fontWeight: "900",
  },
  todayMeDeleteButton: {
    alignItems: "center",
    borderColor: "#4b2a2a",
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    justifyContent: "center",
    minHeight: 28,
    paddingHorizontal: 10,
  },
  todayMeDeleteButtonText: {
    color: "#fca5a5",
    fontSize: 11,
    fontWeight: "900",
  },
  dreamProjectSummaryCard: {
    backgroundColor: "#111111",
    borderColor: "#2f2f2f",
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 14,
    padding: 14,
  },
  dreamProjectSummaryHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  dreamProjectSummaryTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  dreamProjectSummaryPercent: {
    color: "#e5e7eb",
    fontSize: 22,
    fontWeight: "900",
  },
  dreamProjectSummaryTrack: {
    backgroundColor: "#242424",
    borderRadius: 999,
    height: 9,
    overflow: "hidden",
  },
  dreamProjectSummaryFill: {
    backgroundColor: "#34d399",
    borderRadius: 999,
    height: 9,
  },
  dreamProjectSummaryNext: {
    color: "#d1d5db",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
    marginTop: 8,
  },
  consistencyStatusRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 4,
    marginTop: 8,
  },
  consistencyStatusSymbol: {
    color: "#d1d5db",
    fontSize: 17,
    fontWeight: "900",
    lineHeight: 22,
    textAlign: "center",
    width: 24,
  },
  consistencyStatusSymbolComplete: {
    fontSize: 18,
  },
  consistencyWeekdayRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 4,
    marginTop: 2,
  },
  consistencyWeekdayText: {
    color: "#8f8f8f",
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 15,
    textAlign: "center",
    width: 24,
  },
  dreamProjectSummaryNotice: {
    color: "#fbbf24",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 6,
  },
  dreamProgressDetailsBox: {
    backgroundColor: "#0b0b0b",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    marginTop: 10,
    padding: 10,
  },  dreamProjectSummaryStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 10,
  },
  dreamProjectSummaryStat: {
    color: "#aeb4c0",
    fontSize: 12,
    fontWeight: "800",
  },
  dreamPlanBox: {
    backgroundColor: "#141414",
    borderColor: "#2d2d2d",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginTop: 12,
    padding: 12,
  },
  dreamPlanTitle: { color: "#ffffff", fontSize: 15, fontWeight: "900" },
  dreamPlanSubtitle: { color: "#e5e7eb", fontSize: 13, fontWeight: "900" },
  dreamPlanHint: { color: "#aeb4c0", fontSize: 12, lineHeight: 18 },
  dreamPlanWarning: { color: "#fbbf24", fontSize: 12, fontWeight: "800", lineHeight: 18 },
  dreamProgressGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  dreamProgressStat: {
    backgroundColor: "#0b0b0b",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 112,
    padding: 9,
  },
  dreamProgressStatLabel: { color: "#8f8f8f", fontSize: 11, fontWeight: "800" },
  dreamProgressStatValue: { color: "#f2f4f8", fontSize: 17, fontWeight: "900", marginTop: 4 },
  dreamRoutineList: { gap: 8 },
  dreamRoutineRow: {
    backgroundColor: "#101010",
    borderColor: "#292929",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  dreamRoutineTitle: { color: "#f2f4f8", fontSize: 13, fontWeight: "900" },
  dreamRoutineActions: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  dreamRoutineButton: {
    borderColor: "#3a3a3a",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dreamRoutineButtonText: { color: "#d1d5db", fontSize: 12, fontWeight: "900" },
  dreamPlanEditor: { gap: 8, marginTop: 4 },
  dreamPlanInput: {
    backgroundColor: "#0a0a0a",
    borderColor: "#333333",
    borderRadius: 8,
    borderWidth: 1,
    color: "#ffffff",
    fontSize: 13,
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dreamPlanTextArea: { minHeight: 82, textAlignVertical: "top" },  dreamPieceDate: {
    color: "#777777",
    fontSize: 11,
    marginTop: 8,
  },
  dreamPieceActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  dreamPieceActionButton: {
    borderColor: "#4a5568",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dreamPieceActionButtonMuted: {
    borderColor: "#333333",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dreamPieceActionText: {
    color: "#e5e7eb",
    fontSize: 11,
    fontWeight: "800",
  },
  dreamPieceActionTextMuted: {
    color: "#9ca3af",
    fontSize: 11,
    fontWeight: "800",
  },
  dreamPieceStatusText: {
    color: "#aeb4c0",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
    marginTop: 6,
  },
  dreamPieceMoreMenu: {
    backgroundColor: "#151515",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    marginTop: 8,
    padding: 8,
  },
  dreamPieceMoreMenuItem: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  dreamPieceMoreMenuText: {
    color: "#d1d5db",
    fontSize: 12,
    fontWeight: "800",
  },
  dreamPieceDeleteConfirmBox: {
    backgroundColor: "#1b1111",
    borderColor: "#4b2a2a",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 10,
    padding: 10,
  },
  dreamPieceDeleteConfirmText: {
    color: "#f5d0d0",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  dreamPieceCompleteConfirmBox: {
    backgroundColor: "#071b12",
    borderColor: "#1f7a4d",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 10,
    padding: 10,
  },
  dreamPieceCompleteConfirmText: {
    color: "#bbf7d0",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  dreamPieceCompleteButton: {
    alignItems: "center",
    backgroundColor: "#16a34a",
    borderRadius: 999,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: 12,
  },
  dreamPieceCompleteButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  dreamPieceDeleteButton: {
    alignItems: "center",
    backgroundColor: "#ef4444",
    borderRadius: 999,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: 12,
  },
  dreamPieceDeleteButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  linkedProjectBox: {
    backgroundColor: "#151515",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 12,
    padding: 10,
  },
  linkedProjectSectionTitle: {
    color: "#f2f4f8",
    fontSize: 12,
    fontWeight: "900",
  },
  linkedProjectList: {
    gap: 8,
  },
  linkedProjectItem: {
    backgroundColor: "#0d0d0d",
    borderColor: "#242424",
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  linkedProjectTitle: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 19,
  },
  linkedProjectMeta: {
    color: "#aeb4c0",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
  },
  linkedProjectStatus: {
    color: "#9ca3af",
    fontSize: 11,
    fontWeight: "900",
  },
  unlinkedProjectFoldBox: {
    borderColor: "#262626",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 14,
    padding: 10,
  },
  unlinkedProjectFoldRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  unlinkedProjectFoldText: {
    color: "#9ca3af",
    fontSize: 12,
    fontWeight: "800",
  },
  unlinkedProjectFoldAction: {
    color: "#d1d5db",
    fontSize: 12,
    fontWeight: "900",
  },
  unlinkedProjectList: {
    gap: 6,
    marginTop: 8,
  },
  unlinkedProjectRow: {
    paddingVertical: 5,
  },
  unlinkedProjectTitle: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "800",
  },
  dreamFragmentInfoBox: {
    backgroundColor: "#161616",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    padding: 10,
    gap: 4,
  },
  dreamFragmentProgress: {
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
  },
  dreamFragmentJudgement: {
    color: "#aeb4c0",
    fontSize: 12,
    lineHeight: 18,
  },
  dreamFragmentNotice: {
    color: "#9cc7ff",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  dreamEvidenceCard: {
    backgroundColor: "#141414",
    borderColor: "#2f2f2f",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    padding: 10,
    gap: 6,
  },
  dreamEvidenceTitle: {
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 2,
  },
  dreamEvidenceRow: {
    flexDirection: "row",
    gap: 10,
  },
  dreamEvidenceKey: {
    color: "#8b8b8b",
    flexBasis: 110,
    fontSize: 11,
    fontWeight: "800",
  },
  dreamEvidenceValue: {
    color: "#d1d5db",
    flex: 1,
    fontSize: 11,
    lineHeight: 16,
  },
  resumeMaterialCard: {
    backgroundColor: "#151515",
    borderColor: "#303030",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    padding: 10,
    gap: 8,
  },
  resumeMaterialTitle: {
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
  },
  resumeMaterialSection: {
    gap: 2,
  },
  resumeMaterialSectionTitle: {
    color: "#9ca3af",
    fontSize: 11,
    fontWeight: "900",
  },
  resumeMaterialText: {
    color: "#d7d7d7",
    fontSize: 12,
    lineHeight: 18,
  },
  traceHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  traceSurface: {
    gap: 24,
  },
  traceWeekHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  traceMonthToggle: {
    alignItems: "center",
    borderColor: "#303030",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    marginHorizontal: 12,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  traceConstellation: {
    marginBottom: 2,
    minHeight: 62,
  },
  traceWeekDateRow: {
    flexDirection: "row",
    marginBottom: 5,
  },
  traceWeekDayButton: {
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  traceWeekDateText: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "800",
  },
  traceWeekDateTextToday: {
    color: "#f2f4f8",
  },
  traceWeekDateTextSelected: {
    color: "#ffffff",
    fontWeight: "900",
  },
  traceStarRow: {
    alignItems: "center",
    flexDirection: "row",
  },
  traceStarSlot: {
    alignItems: "center",
    minHeight: 42,
    width: 30,
  },
  traceStarButton: {
    alignItems: "center",
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  traceStarSymbol: {
    color: "#d1d5db",
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 24,
    textAlign: "center",
  },
  traceStarSymbolSelected: {
    color: "#ffffff",
    fontSize: 20,
  },
  traceStarSymbolToday: {
    color: "#f2f4f8",
  },
  traceStarLine: {
    backgroundColor: "#2b2b2b",
    flex: 1,
    height: 1,
    marginBottom: 14,
  },
  traceTodayLabel: {
    color: "#8f8f8f",
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 12,
  },
  traceMonthPanel: {
    backgroundColor: "#0d0d0d",
    borderColor: "#1f1f1f",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: -8,
    marginBottom: 2,
    padding: 10,
  },
  calendarHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  calendarNavButton: {
    alignItems: "center",
    backgroundColor: "#111111",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  calendarNavText: { color: "#ffffff", fontSize: 24, lineHeight: 26 },
  calendarMonthTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  weekdayRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  weekdayText: {
    color: "#8f8f8f",
    flex: 1,
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  calendarDayCell: {
    alignItems: "center",
    aspectRatio: 1,
    borderRadius: 8,
    justifyContent: "center",
    position: "relative",
    width: `${100 / 7}%`,
  },
  calendarDayMuted: { opacity: 0.36 },
  calendarDaySelected: {
    backgroundColor: "#f2f4f8",
  },
  calendarDayText: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: "800",
  },
  calendarDayTextMuted: { color: "#8f8f8f" },
  calendarDayTextSelected: { color: "#050505" },
  calendarDot: {
    backgroundColor: "#34d399",
    borderRadius: 999,
    bottom: 7,
    height: 5,
    position: "absolute",
    width: 5,
  },
  traceDetail: {
    backgroundColor: "transparent",
    paddingVertical: 2,
  },
  traceDateTitle: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 6,
  },
  traceDetailHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 18,
  },
  traceHeaderActions: {
    alignItems: "center",
    flexDirection: "row",
    flexShrink: 0,
    gap: 6,
  },
  traceTodayButton: {
    borderColor: "#303030",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  traceTodayButtonText: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "900",
  },
  traceAddButton: {
    borderColor: "#303030",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  traceAddButtonText: {
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
  },
  traceAddPanel: {
    backgroundColor: "#111111",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 14,
    padding: 10,
  },
  traceAddPanelTitle: {
    color: "#f2f4f8",
    fontSize: 13,
    fontWeight: "900",
  },
  traceAddModeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  traceAddModeButton: {
    borderColor: "#333333",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  traceAddModeButtonActive: {
    backgroundColor: "#f2f4f8",
    borderColor: "#f2f4f8",
  },
  traceAddModeText: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "800",
  },
  traceAddModeTextActive: {
    color: "#050505",
  },
  traceAddForm: {
    gap: 8,
  },
  traceAddInput: {
    backgroundColor: "#0a0a0a",
    borderColor: "#303030",
    borderRadius: 8,
    borderWidth: 1,
    color: "#ffffff",
    fontSize: 13,
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  traceReminderRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  traceReminderChip: {
    borderColor: "#333333",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  traceReminderChipActive: {
    backgroundColor: "#243b2f",
    borderColor: "#34d399",
  },
  traceReminderChipText: {
    color: "#9ca3af",
    fontSize: 11,
    fontWeight: "800",
  },
  traceReminderChipTextActive: {
    color: "#bbf7d0",
  },
  traceAddSaveButton: {
    alignItems: "center",
    backgroundColor: "#f2f4f8",
    borderRadius: 999,
    justifyContent: "center",
    minHeight: 36,
  },
  traceAddSaveButtonDisabled: {
    opacity: 0.45,
  },
  traceAddSaveButtonText: {
    color: "#050505",
    fontSize: 13,
    fontWeight: "900",
  },
  traceDetailTitle: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 12,
  },
  traceRemainingTitle: {
    marginTop: 24,
  },
  traceEmptyBox: {
    alignItems: "center",
    minHeight: 82,
    justifyContent: "center",
  },
  traceEmptyText: {
    color: "#a9a9a9",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  traceEmptySmallText: {
    color: "#a9a9a9",
    fontSize: 13,
    lineHeight: 20,
  },
  traceEmptyDayText: {
    color: "#a9a9a9",
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 4,
  },
  traceRecordList: {
    marginTop: 2,
  },
  traceRecordRow: {
    alignItems: "flex-start",
    borderBottomColor: "#1c1c1c",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingVertical: 12,
  },
  traceScheduleRow: {
    borderBottomColor: "#1c1c1c",
    borderBottomWidth: 1,
    paddingVertical: 12,
  },
  traceScheduleRowMain: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  traceRecordRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  traceRecordIcon: {
    color: "#f2f4f8",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    width: 22,
  },
  traceRecordTime: {
    color: "#9ca3af",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 22,
    width: 42,
  },
  traceRecordTextBlock: {
    flex: 1,
  },
  traceTodoCompleteButton: {
    alignItems: "center",
    height: 24,
    justifyContent: "center",
    width: 22,
  },
  traceTodoCompleteText: {
    color: "#d1d5db",
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 22,
  },
  traceScheduleMenuButton: {
    alignItems: "center",
    borderColor: "#2f2f2f",
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  traceScheduleMenuButtonText: {
    color: "#d1d5db",
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 20,
  },
  traceScheduleMenuPanel: {
    alignSelf: "flex-end",
    borderColor: "#2a2a2a",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    minWidth: 168,
    overflow: "hidden",
  },
  traceScheduleMenuItem: {
    borderBottomColor: "#202020",
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  traceScheduleMenuItemText: {
    color: "#d1d5db",
    fontSize: 12,
    fontWeight: "800",
  },
  traceScheduleMenuDangerText: {
    color: "#fca5a5",
    fontSize: 12,
    fontWeight: "900",
  },
  traceItemSource: {
    color: "#777777",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  traceAdjacentRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 2,
    minHeight: 38,
  },
  traceAdjacentText: {
    color: "#aeb4c0",
    fontSize: 13,
    fontWeight: "800",
  },
  traceLongRecordBox: {
    backgroundColor: "#111111",
    borderColor: "#202020",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 28,
    padding: 14,
  },
  traceLongRecordHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  traceLongRecordTitle: {
    color: "#ffffff",
    flex: 1,
    fontSize: 15,
    fontWeight: "900",
  },
  traceLongRecordAction: {
    borderColor: "#333333",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  traceLongRecordActionText: {
    color: "#d1d5db",
    fontSize: 12,
    fontWeight: "900",
  },
  traceLongRecordEditor: {
    gap: 8,
  },
  traceLongRecordEditorHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  traceLongRecordEditorTitle: {
    color: "#f2f4f8",
    fontSize: 13,
    fontWeight: "900",
  },
  traceLongRecordLabel: {
    color: "#8f8f8f",
    fontSize: 12,
    fontWeight: "800",
  },
  traceLongRecordInput: {
    backgroundColor: "#0a0a0a",
    borderColor: "#303030",
    borderRadius: 8,
    borderWidth: 1,
    color: "#ffffff",
    fontSize: 13,
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  traceLongRecordBodyInput: {
    minHeight: 112,
  },
  traceLongRecordSaveButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: "#f2f4f8",
    borderRadius: 999,
    justifyContent: "center",
    minHeight: 34,
    paddingHorizontal: 16,
  },
  traceLongRecordSaveButtonText: {
    color: "#050505",
    fontSize: 13,
    fontWeight: "900",
  },
  traceLongRecordContent: {
    gap: 8,
  },
  traceLongRecordContentTitle: {
    color: "#f2f4f8",
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 20,
  },
  traceLongRecordBody: {
    color: "#d7d7d7",
    fontSize: 14,
    lineHeight: 21,
  },
  traceLongRecordMoreButton: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  traceLongRecordSavedAt: {
    alignSelf: "flex-end",
    color: "#777777",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  traceUpcomingBox: {
    marginTop: 4,
    paddingTop: 6,
  },
  traceUpcomingEmptyRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  traceUpcomingRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
    paddingBottom: 14,
  },
  traceUpcomingTimeline: {
    borderLeftColor: "#333333",
    borderLeftWidth: 1,
    marginLeft: 4,
    paddingLeft: 12,
  },
  traceUpcomingDate: {
    color: "#9ca3af",
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 22,
    width: 58,
  },
  traceGroup: { marginBottom: 14 },
  traceGroupTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 8,
  },
  traceListItem: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    marginBottom: 8,
  },
  traceListTextBlock: { flex: 1 },
  traceItemTitle: {
    color: "#f2f4f8",
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  traceItemDone: {
    color: "#8f8f8f",
    textDecorationLine: "line-through",
  },
  traceItemMemo: {
    color: "#9ca3af",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 3,
  },
  traceDeleteButton: {
    alignItems: "center",
    borderColor: "#3a3a3a",
    borderRadius: 6,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 30,
    paddingHorizontal: 9,
  },
  traceDeleteButtonText: {
    color: "#d1d5db",
    fontSize: 12,
    fontWeight: "800",
  },
  traceCleanupTextButton: {
    alignSelf: "center",
    marginTop: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  traceCleanupTextButtonText: {
    color: "#777777",
    fontSize: 12,
    fontWeight: "800",
  },
  todoCheck: {
    alignItems: "center",
    borderColor: "#555555",
    borderRadius: 6,
    borderWidth: 1,
    height: 22,
    justifyContent: "center",
    marginTop: 1,
    width: 22,
  },
  todoCheckDone: {
    backgroundColor: "#34d399",
    borderColor: "#34d399",
  },
  todoCheckText: {
    color: "#050505",
    fontSize: 14,
    fontWeight: "900",
  },
});
